---

- name: elasticsearch data dir
  file: path=/data state=directory owner=elasticsearch group=elasticsearch mode=0755

- name: elasticsearch data elasticsearch dir
  file: path=/data/elasticsearch state=directory owner=elasticsearch group=elasticsearch mode=0755

- name: setup elasticsearch default
  template: src=etc/default/elasticsearch.j2 dest=/etc/default/elasticsearch owner=root group=root mode=0644

- name: setup elasticsearch 
  template: src=etc/systemd/elasticsearch.service.j2 dest=/etc/systemd/system/elasticsearch.service owner=root group=root mode=0777
  notify: reload systemd
