---
- name: Kibana apt source list
  apt_repository: repo='deb http://packages.elastic.co/kibana/4.4/debian stable main' state=present
  notify: update apt

- name: Install Kibana
  apt: name=kibana state=present

- name: Kibana service
  service: name=kibana state=started enabled=yes
